SELECT substr(sale_date,1,7) AS yyyy_mm, customer AS customer 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '1' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#John#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '1' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#John#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '1' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#John#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#John' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '2' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Mario#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '2' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Mario#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '2' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Mario#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Mario' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '3' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Frank#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '3' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Frank#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '3' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Frank#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Frank' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '4' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Otto#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '4' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Otto#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '4' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Otto#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '4' THEN sale_amount ELSE NULL END) AS 'UK#Otto' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '5' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Susan#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '5' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Susan#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '5' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Susan#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '5' THEN sale_amount ELSE NULL END) AS 'UK#Susan' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '6' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Martin#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '6' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Martin#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '6' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Martin#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '6' THEN sale_amount ELSE NULL END) AS 'UK#Martin' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '7' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Mary#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '7' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Mary#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '7' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Mary#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '7' THEN sale_amount ELSE NULL END) AS 'UK#Mary' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '8' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Bill#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '8' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Bill#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '8' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Bill#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '8' THEN sale_amount ELSE NULL END) AS 'UK#Bill' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '9' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#June#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '9' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#June#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '9' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#June#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '9' THEN sale_amount ELSE NULL END) AS 'UK#June' 
,SUM(CASE WHEN country_id = '1' THEN sale_amount ELSE NULL END) AS 'UK' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '1' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#John#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '1' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#John#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '1' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#John#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#John' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '2' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Mario#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '2' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Mario#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '2' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Mario#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Mario' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '3' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Frank#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '3' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Frank#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '3' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Frank#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Frank' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '4' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Otto#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '4' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Otto#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '4' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Otto#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '4' THEN sale_amount ELSE NULL END) AS 'Germany#Otto' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '5' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Susan#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '5' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Susan#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '5' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Susan#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '5' THEN sale_amount ELSE NULL END) AS 'Germany#Susan' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '6' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Martin#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '6' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Martin#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '6' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Martin#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '6' THEN sale_amount ELSE NULL END) AS 'Germany#Martin' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '7' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Mary#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '7' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Mary#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '7' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Mary#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '7' THEN sale_amount ELSE NULL END) AS 'Germany#Mary' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '8' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Bill#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '8' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Bill#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '8' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Bill#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '8' THEN sale_amount ELSE NULL END) AS 'Germany#Bill' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '9' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#June#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '9' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#June#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '9' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#June#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '9' THEN sale_amount ELSE NULL END) AS 'Germany#June' 
,SUM(CASE WHEN country_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '1' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#John#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '1' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#John#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '1' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#John#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#John' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '2' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Mario#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '2' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Mario#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '2' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Mario#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Mario' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '3' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Frank#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '3' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Frank#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '3' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Frank#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Frank' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '4' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Otto#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '4' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Otto#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '4' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Otto#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '4' THEN sale_amount ELSE NULL END) AS 'Italy#Otto' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '5' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Susan#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '5' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Susan#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '5' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Susan#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '5' THEN sale_amount ELSE NULL END) AS 'Italy#Susan' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '6' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Martin#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '6' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Martin#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '6' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Martin#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '6' THEN sale_amount ELSE NULL END) AS 'Italy#Martin' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '7' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Mary#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '7' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Mary#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '7' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Mary#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '7' THEN sale_amount ELSE NULL END) AS 'Italy#Mary' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '8' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Bill#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '8' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Bill#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '8' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Bill#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '8' THEN sale_amount ELSE NULL END) AS 'Italy#Bill' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '9' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#June#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '9' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#June#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '9' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#June#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '9' THEN sale_amount ELSE NULL END) AS 'Italy#June' 
,SUM(CASE WHEN country_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy' 
,SUM(sale_amount) AS total
 FROM xtab_sales 
 INNER JOIN xtab_customers 
 ON (xtab_sales.customer_id=xtab_customers.customer_id) 
 INNER JOIN xtab_person 
 ON (xtab_sales.person_id=xtab_person.person_id)
 INNER JOIN xtab_class 
 ON (xtab_sales.class_id=xtab_class.class_id)
 INNER JOIN xtab_locations 
 ON (xtab_locations.loc_id=xtab_person.loc_id)
 GROUP BY yyyy_mm, customer
UNION
 SELECT substr(sale_date,1,7) AS yyyy_mm, 'zzzz' AS customer 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '1' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#John#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '1' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#John#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '1' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#John#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#John' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '2' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Mario#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '2' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Mario#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '2' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Mario#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Mario' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '3' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Frank#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '3' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Frank#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '3' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Frank#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Frank' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '4' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Otto#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '4' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Otto#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '4' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Otto#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '4' THEN sale_amount ELSE NULL END) AS 'UK#Otto' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '5' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Susan#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '5' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Susan#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '5' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Susan#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '5' THEN sale_amount ELSE NULL END) AS 'UK#Susan' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '6' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Martin#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '6' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Martin#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '6' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Martin#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '6' THEN sale_amount ELSE NULL END) AS 'UK#Martin' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '7' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Mary#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '7' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Mary#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '7' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Mary#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '7' THEN sale_amount ELSE NULL END) AS 'UK#Mary' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '8' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Bill#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '8' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Bill#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '8' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Bill#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '8' THEN sale_amount ELSE NULL END) AS 'UK#Bill' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '9' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#June#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '9' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#June#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '9' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#June#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '9' THEN sale_amount ELSE NULL END) AS 'UK#June' 
,SUM(CASE WHEN country_id = '1' THEN sale_amount ELSE NULL END) AS 'UK' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '1' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#John#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '1' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#John#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '1' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#John#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#John' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '2' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Mario#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '2' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Mario#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '2' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Mario#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Mario' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '3' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Frank#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '3' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Frank#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '3' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Frank#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Frank' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '4' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Otto#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '4' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Otto#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '4' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Otto#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '4' THEN sale_amount ELSE NULL END) AS 'Germany#Otto' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '5' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Susan#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '5' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Susan#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '5' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Susan#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '5' THEN sale_amount ELSE NULL END) AS 'Germany#Susan' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '6' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Martin#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '6' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Martin#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '6' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Martin#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '6' THEN sale_amount ELSE NULL END) AS 'Germany#Martin' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '7' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Mary#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '7' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Mary#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '7' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Mary#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '7' THEN sale_amount ELSE NULL END) AS 'Germany#Mary' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '8' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Bill#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '8' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Bill#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '8' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Bill#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '8' THEN sale_amount ELSE NULL END) AS 'Germany#Bill' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '9' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#June#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '9' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#June#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '9' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#June#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '9' THEN sale_amount ELSE NULL END) AS 'Germany#June' 
,SUM(CASE WHEN country_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '1' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#John#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '1' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#John#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '1' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#John#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#John' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '2' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Mario#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '2' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Mario#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '2' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Mario#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Mario' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '3' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Frank#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '3' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Frank#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '3' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Frank#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Frank' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '4' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Otto#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '4' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Otto#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '4' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Otto#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '4' THEN sale_amount ELSE NULL END) AS 'Italy#Otto' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '5' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Susan#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '5' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Susan#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '5' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Susan#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '5' THEN sale_amount ELSE NULL END) AS 'Italy#Susan' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '6' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Martin#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '6' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Martin#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '6' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Martin#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '6' THEN sale_amount ELSE NULL END) AS 'Italy#Martin' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '7' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Mary#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '7' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Mary#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '7' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Mary#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '7' THEN sale_amount ELSE NULL END) AS 'Italy#Mary' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '8' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Bill#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '8' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Bill#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '8' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Bill#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '8' THEN sale_amount ELSE NULL END) AS 'Italy#Bill' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '9' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#June#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '9' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#June#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '9' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#June#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '9' THEN sale_amount ELSE NULL END) AS 'Italy#June' 
,SUM(CASE WHEN country_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy' 
,SUM(sale_amount) AS total
 FROM xtab_sales 
 INNER JOIN xtab_customers 
 ON (xtab_sales.customer_id=xtab_customers.customer_id) 
 INNER JOIN xtab_person 
 ON (xtab_sales.person_id=xtab_person.person_id)
 INNER JOIN xtab_class 
 ON (xtab_sales.class_id=xtab_class.class_id)
 INNER JOIN xtab_locations 
 ON (xtab_locations.loc_id=xtab_person.loc_id)
 GROUP BY yyyy_mm
UNION
 SELECT 'zzzz' AS yyyy_mm, 'zzzz' AS customer
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '1' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#John#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '1' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#John#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '1' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#John#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#John' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '2' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Mario#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '2' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Mario#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '2' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Mario#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Mario' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '3' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Frank#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '3' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Frank#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '3' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Frank#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Frank' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '4' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Otto#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '4' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Otto#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '4' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Otto#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '4' THEN sale_amount ELSE NULL END) AS 'UK#Otto' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '5' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Susan#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '5' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Susan#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '5' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Susan#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '5' THEN sale_amount ELSE NULL END) AS 'UK#Susan' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '6' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Martin#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '6' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Martin#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '6' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Martin#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '6' THEN sale_amount ELSE NULL END) AS 'UK#Martin' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '7' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Mary#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '7' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Mary#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '7' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Mary#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '7' THEN sale_amount ELSE NULL END) AS 'UK#Mary' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '8' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#Bill#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '8' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#Bill#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '8' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#Bill#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '8' THEN sale_amount ELSE NULL END) AS 'UK#Bill' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '9' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'UK#June#software' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '9' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'UK#June#hardware' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '9' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'UK#June#services' 
,SUM(CASE WHEN country_id = '1' AND xtab_person.person_id = '9' THEN sale_amount ELSE NULL END) AS 'UK#June' 
,SUM(CASE WHEN country_id = '1' THEN sale_amount ELSE NULL END) AS 'UK' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '1' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#John#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '1' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#John#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '1' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#John#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#John' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '2' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Mario#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '2' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Mario#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '2' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Mario#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Mario' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '3' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Frank#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '3' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Frank#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '3' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Frank#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Frank' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '4' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Otto#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '4' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Otto#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '4' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Otto#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '4' THEN sale_amount ELSE NULL END) AS 'Germany#Otto' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '5' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Susan#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '5' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Susan#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '5' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Susan#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '5' THEN sale_amount ELSE NULL END) AS 'Germany#Susan' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '6' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Martin#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '6' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Martin#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '6' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Martin#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '6' THEN sale_amount ELSE NULL END) AS 'Germany#Martin' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '7' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Mary#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '7' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Mary#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '7' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Mary#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '7' THEN sale_amount ELSE NULL END) AS 'Germany#Mary' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '8' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#Bill#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '8' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#Bill#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '8' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#Bill#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '8' THEN sale_amount ELSE NULL END) AS 'Germany#Bill' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '9' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Germany#June#software' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '9' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany#June#hardware' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '9' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Germany#June#services' 
,SUM(CASE WHEN country_id = '2' AND xtab_person.person_id = '9' THEN sale_amount ELSE NULL END) AS 'Germany#June' 
,SUM(CASE WHEN country_id = '2' THEN sale_amount ELSE NULL END) AS 'Germany' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '1' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#John#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '1' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#John#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '1' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#John#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#John' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '2' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Mario#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '2' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Mario#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '2' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Mario#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Mario' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '3' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Frank#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '3' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Frank#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '3' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Frank#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Frank' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '4' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Otto#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '4' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Otto#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '4' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Otto#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '4' THEN sale_amount ELSE NULL END) AS 'Italy#Otto' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '5' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Susan#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '5' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Susan#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '5' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Susan#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '5' THEN sale_amount ELSE NULL END) AS 'Italy#Susan' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '6' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Martin#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '6' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Martin#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '6' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Martin#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '6' THEN sale_amount ELSE NULL END) AS 'Italy#Martin' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '7' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Mary#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '7' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Mary#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '7' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Mary#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '7' THEN sale_amount ELSE NULL END) AS 'Italy#Mary' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '8' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#Bill#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '8' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#Bill#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '8' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#Bill#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '8' THEN sale_amount ELSE NULL END) AS 'Italy#Bill' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '9' AND xtab_class.class_id = '1' THEN sale_amount ELSE NULL END) AS 'Italy#June#software' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '9' AND xtab_class.class_id = '2' THEN sale_amount ELSE NULL END) AS 'Italy#June#hardware' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '9' AND xtab_class.class_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy#June#services' 
,SUM(CASE WHEN country_id = '3' AND xtab_person.person_id = '9' THEN sale_amount ELSE NULL END) AS 'Italy#June' 
,SUM(CASE WHEN country_id = '3' THEN sale_amount ELSE NULL END) AS 'Italy' 
,SUM(sale_amount) AS total
 FROM xtab_sales 
 INNER JOIN xtab_customers 
 ON (xtab_sales.customer_id=xtab_customers.customer_id) 
 INNER JOIN xtab_person 
 ON (xtab_sales.person_id=xtab_person.person_id)
 INNER JOIN xtab_class 
 ON (xtab_sales.class_id=xtab_class.class_id)
 INNER JOIN xtab_locations 
 ON (xtab_locations.loc_id=xtab_person.loc_id)
 ORDER BY yyyy_mm, customer
