SELECT CASE WHEN country="Italy" THEN "S" ELSE "N" END AS Area, country AS country, loc AS location 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld001 -- (xcount#pers#employee#f) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld002 -- (xcount#pers#employee#m) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld003 -- (xcount#pers#employee) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld004 -- (xcount#pers#contractor#f) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld005 -- (xcount#pers#contractor#m) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld006 -- (xcount#pers#contractor) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld007 -- (xcount#pers#consultant#f) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld008 -- (xcount#pers#consultant#m) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld009 -- (xcount#pers#consultant) 
,COUNT(CASE WHEN dept_id = '1' THEN person_id ELSE NULL END) AS xfld010 -- (xcount#pers) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld011 -- (xcount#xtab_sales#employee#f) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld012 -- (xcount#xtab_sales#employee#m) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld013 -- (xcount#xtab_sales#employee) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld014 -- (xcount#xtab_sales#contractor#f) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld015 -- (xcount#xtab_sales#contractor#m) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld016 -- (xcount#xtab_sales#contractor) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld017 -- (xcount#xtab_sales#consultant#f) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld018 -- (xcount#xtab_sales#consultant#m) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld019 -- (xcount#xtab_sales#consultant) 
,COUNT(CASE WHEN dept_id = '2' THEN person_id ELSE NULL END) AS xfld020 -- (xcount#xtab_sales) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld021 -- (xcount#dev#employee#f) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld022 -- (xcount#dev#employee#m) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld023 -- (xcount#dev#employee) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld024 -- (xcount#dev#contractor#f) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld025 -- (xcount#dev#contractor#m) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld026 -- (xcount#dev#contractor) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld027 -- (xcount#dev#consultant#f) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld028 -- (xcount#dev#consultant#m) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld029 -- (xcount#dev#consultant) 
,COUNT(CASE WHEN dept_id = '3' THEN person_id ELSE NULL END) AS xfld030 -- (xcount#dev) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld031 -- (xcount#research#employee#f) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld032 -- (xcount#research#employee#m) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld033 -- (xcount#research#employee) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld034 -- (xcount#research#contractor#f) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld035 -- (xcount#research#contractor#m) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld036 -- (xcount#research#contractor) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld037 -- (xcount#research#consultant#f) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld038 -- (xcount#research#consultant#m) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld039 -- (xcount#research#consultant) 
,COUNT(CASE WHEN dept_id = '4' THEN person_id ELSE NULL END) AS xfld040 -- (xcount#research) 
,COUNT(person_id) AS xcount
,SUM(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld041 -- (xsum#pers#employee#f) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld042 -- (xsum#pers#employee#m) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld043 -- (xsum#pers#employee) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld044 -- (xsum#pers#contractor#f) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld045 -- (xsum#pers#contractor#m) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld046 -- (xsum#pers#contractor) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld047 -- (xsum#pers#consultant#f) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld048 -- (xsum#pers#consultant#m) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld049 -- (xsum#pers#consultant) 
,SUM(CASE WHEN dept_id = '1' THEN salary ELSE NULL END) AS xfld050 -- (xsum#pers) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld051 -- (xsum#xtab_sales#employee#f) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld052 -- (xsum#xtab_sales#employee#m) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld053 -- (xsum#xtab_sales#employee) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld054 -- (xsum#xtab_sales#contractor#f) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld055 -- (xsum#xtab_sales#contractor#m) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld056 -- (xsum#xtab_sales#contractor) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld057 -- (xsum#xtab_sales#consultant#f) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld058 -- (xsum#xtab_sales#consultant#m) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld059 -- (xsum#xtab_sales#consultant) 
,SUM(CASE WHEN dept_id = '2' THEN salary ELSE NULL END) AS xfld060 -- (xsum#xtab_sales) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld061 -- (xsum#dev#employee#f) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld062 -- (xsum#dev#employee#m) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld063 -- (xsum#dev#employee) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld064 -- (xsum#dev#contractor#f) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld065 -- (xsum#dev#contractor#m) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld066 -- (xsum#dev#contractor) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld067 -- (xsum#dev#consultant#f) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld068 -- (xsum#dev#consultant#m) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld069 -- (xsum#dev#consultant) 
,SUM(CASE WHEN dept_id = '3' THEN salary ELSE NULL END) AS xfld070 -- (xsum#dev) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld071 -- (xsum#research#employee#f) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld072 -- (xsum#research#employee#m) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld073 -- (xsum#research#employee) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld074 -- (xsum#research#contractor#f) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld075 -- (xsum#research#contractor#m) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld076 -- (xsum#research#contractor) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld077 -- (xsum#research#consultant#f) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld078 -- (xsum#research#consultant#m) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld079 -- (xsum#research#consultant) 
,SUM(CASE WHEN dept_id = '4' THEN salary ELSE NULL END) AS xfld080 -- (xsum#research) 
,SUM(salary) AS xsum
 FROM xtab_person 
 INNER JOIN xtab_locations 
 ON (xtab_person.loc_id=xtab_locations.loc_id) 
 INNER JOIN xtab_countries 
 ON (xtab_countries.country_id=xtab_locations.country_id)
 GROUP BY Area, country, location
UNION
 SELECT CASE WHEN country="Italy" THEN "S" ELSE "N" END AS Area, country AS country, 'zzzz' AS location 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld001 -- (xcount#pers#employee#f) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld002 -- (xcount#pers#employee#m) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld003 -- (xcount#pers#employee) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld004 -- (xcount#pers#contractor#f) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld005 -- (xcount#pers#contractor#m) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld006 -- (xcount#pers#contractor) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld007 -- (xcount#pers#consultant#f) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld008 -- (xcount#pers#consultant#m) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld009 -- (xcount#pers#consultant) 
,COUNT(CASE WHEN dept_id = '1' THEN person_id ELSE NULL END) AS xfld010 -- (xcount#pers) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld011 -- (xcount#xtab_sales#employee#f) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld012 -- (xcount#xtab_sales#employee#m) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld013 -- (xcount#xtab_sales#employee) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld014 -- (xcount#xtab_sales#contractor#f) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld015 -- (xcount#xtab_sales#contractor#m) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld016 -- (xcount#xtab_sales#contractor) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld017 -- (xcount#xtab_sales#consultant#f) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld018 -- (xcount#xtab_sales#consultant#m) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld019 -- (xcount#xtab_sales#consultant) 
,COUNT(CASE WHEN dept_id = '2' THEN person_id ELSE NULL END) AS xfld020 -- (xcount#xtab_sales) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld021 -- (xcount#dev#employee#f) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld022 -- (xcount#dev#employee#m) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld023 -- (xcount#dev#employee) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld024 -- (xcount#dev#contractor#f) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld025 -- (xcount#dev#contractor#m) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld026 -- (xcount#dev#contractor) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld027 -- (xcount#dev#consultant#f) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld028 -- (xcount#dev#consultant#m) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld029 -- (xcount#dev#consultant) 
,COUNT(CASE WHEN dept_id = '3' THEN person_id ELSE NULL END) AS xfld030 -- (xcount#dev) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld031 -- (xcount#research#employee#f) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld032 -- (xcount#research#employee#m) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld033 -- (xcount#research#employee) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld034 -- (xcount#research#contractor#f) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld035 -- (xcount#research#contractor#m) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld036 -- (xcount#research#contractor) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld037 -- (xcount#research#consultant#f) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld038 -- (xcount#research#consultant#m) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld039 -- (xcount#research#consultant) 
,COUNT(CASE WHEN dept_id = '4' THEN person_id ELSE NULL END) AS xfld040 -- (xcount#research) 
,COUNT(person_id) AS xcount
,SUM(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld041 -- (xsum#pers#employee#f) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld042 -- (xsum#pers#employee#m) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld043 -- (xsum#pers#employee) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld044 -- (xsum#pers#contractor#f) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld045 -- (xsum#pers#contractor#m) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld046 -- (xsum#pers#contractor) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld047 -- (xsum#pers#consultant#f) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld048 -- (xsum#pers#consultant#m) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld049 -- (xsum#pers#consultant) 
,SUM(CASE WHEN dept_id = '1' THEN salary ELSE NULL END) AS xfld050 -- (xsum#pers) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld051 -- (xsum#xtab_sales#employee#f) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld052 -- (xsum#xtab_sales#employee#m) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld053 -- (xsum#xtab_sales#employee) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld054 -- (xsum#xtab_sales#contractor#f) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld055 -- (xsum#xtab_sales#contractor#m) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld056 -- (xsum#xtab_sales#contractor) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld057 -- (xsum#xtab_sales#consultant#f) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld058 -- (xsum#xtab_sales#consultant#m) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld059 -- (xsum#xtab_sales#consultant) 
,SUM(CASE WHEN dept_id = '2' THEN salary ELSE NULL END) AS xfld060 -- (xsum#xtab_sales) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld061 -- (xsum#dev#employee#f) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld062 -- (xsum#dev#employee#m) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld063 -- (xsum#dev#employee) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld064 -- (xsum#dev#contractor#f) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld065 -- (xsum#dev#contractor#m) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld066 -- (xsum#dev#contractor) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld067 -- (xsum#dev#consultant#f) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld068 -- (xsum#dev#consultant#m) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld069 -- (xsum#dev#consultant) 
,SUM(CASE WHEN dept_id = '3' THEN salary ELSE NULL END) AS xfld070 -- (xsum#dev) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld071 -- (xsum#research#employee#f) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld072 -- (xsum#research#employee#m) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld073 -- (xsum#research#employee) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld074 -- (xsum#research#contractor#f) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld075 -- (xsum#research#contractor#m) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld076 -- (xsum#research#contractor) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld077 -- (xsum#research#consultant#f) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld078 -- (xsum#research#consultant#m) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld079 -- (xsum#research#consultant) 
,SUM(CASE WHEN dept_id = '4' THEN salary ELSE NULL END) AS xfld080 -- (xsum#research) 
,SUM(salary) AS xsum
 FROM xtab_person 
 INNER JOIN xtab_locations 
 ON (xtab_person.loc_id=xtab_locations.loc_id) 
 INNER JOIN xtab_countries 
 ON (xtab_countries.country_id=xtab_locations.country_id)
 GROUP BY Area, country
UNION
 SELECT CASE WHEN country="Italy" THEN "S" ELSE "N" END AS Area, 'zzzz' AS country, 'zzzz' AS location 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld001 -- (xcount#pers#employee#f) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld002 -- (xcount#pers#employee#m) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld003 -- (xcount#pers#employee) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld004 -- (xcount#pers#contractor#f) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld005 -- (xcount#pers#contractor#m) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld006 -- (xcount#pers#contractor) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld007 -- (xcount#pers#consultant#f) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld008 -- (xcount#pers#consultant#m) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld009 -- (xcount#pers#consultant) 
,COUNT(CASE WHEN dept_id = '1' THEN person_id ELSE NULL END) AS xfld010 -- (xcount#pers) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld011 -- (xcount#xtab_sales#employee#f) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld012 -- (xcount#xtab_sales#employee#m) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld013 -- (xcount#xtab_sales#employee) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld014 -- (xcount#xtab_sales#contractor#f) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld015 -- (xcount#xtab_sales#contractor#m) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld016 -- (xcount#xtab_sales#contractor) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld017 -- (xcount#xtab_sales#consultant#f) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld018 -- (xcount#xtab_sales#consultant#m) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld019 -- (xcount#xtab_sales#consultant) 
,COUNT(CASE WHEN dept_id = '2' THEN person_id ELSE NULL END) AS xfld020 -- (xcount#xtab_sales) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld021 -- (xcount#dev#employee#f) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld022 -- (xcount#dev#employee#m) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld023 -- (xcount#dev#employee) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld024 -- (xcount#dev#contractor#f) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld025 -- (xcount#dev#contractor#m) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld026 -- (xcount#dev#contractor) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld027 -- (xcount#dev#consultant#f) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld028 -- (xcount#dev#consultant#m) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld029 -- (xcount#dev#consultant) 
,COUNT(CASE WHEN dept_id = '3' THEN person_id ELSE NULL END) AS xfld030 -- (xcount#dev) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld031 -- (xcount#research#employee#f) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld032 -- (xcount#research#employee#m) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld033 -- (xcount#research#employee) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld034 -- (xcount#research#contractor#f) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld035 -- (xcount#research#contractor#m) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld036 -- (xcount#research#contractor) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld037 -- (xcount#research#consultant#f) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld038 -- (xcount#research#consultant#m) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld039 -- (xcount#research#consultant) 
,COUNT(CASE WHEN dept_id = '4' THEN person_id ELSE NULL END) AS xfld040 -- (xcount#research) 
,COUNT(person_id) AS xcount
,SUM(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld041 -- (xsum#pers#employee#f) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld042 -- (xsum#pers#employee#m) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld043 -- (xsum#pers#employee) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld044 -- (xsum#pers#contractor#f) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld045 -- (xsum#pers#contractor#m) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld046 -- (xsum#pers#contractor) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld047 -- (xsum#pers#consultant#f) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld048 -- (xsum#pers#consultant#m) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld049 -- (xsum#pers#consultant) 
,SUM(CASE WHEN dept_id = '1' THEN salary ELSE NULL END) AS xfld050 -- (xsum#pers) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld051 -- (xsum#xtab_sales#employee#f) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld052 -- (xsum#xtab_sales#employee#m) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld053 -- (xsum#xtab_sales#employee) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld054 -- (xsum#xtab_sales#contractor#f) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld055 -- (xsum#xtab_sales#contractor#m) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld056 -- (xsum#xtab_sales#contractor) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld057 -- (xsum#xtab_sales#consultant#f) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld058 -- (xsum#xtab_sales#consultant#m) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld059 -- (xsum#xtab_sales#consultant) 
,SUM(CASE WHEN dept_id = '2' THEN salary ELSE NULL END) AS xfld060 -- (xsum#xtab_sales) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld061 -- (xsum#dev#employee#f) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld062 -- (xsum#dev#employee#m) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld063 -- (xsum#dev#employee) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld064 -- (xsum#dev#contractor#f) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld065 -- (xsum#dev#contractor#m) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld066 -- (xsum#dev#contractor) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld067 -- (xsum#dev#consultant#f) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld068 -- (xsum#dev#consultant#m) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld069 -- (xsum#dev#consultant) 
,SUM(CASE WHEN dept_id = '3' THEN salary ELSE NULL END) AS xfld070 -- (xsum#dev) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld071 -- (xsum#research#employee#f) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld072 -- (xsum#research#employee#m) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld073 -- (xsum#research#employee) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld074 -- (xsum#research#contractor#f) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld075 -- (xsum#research#contractor#m) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld076 -- (xsum#research#contractor) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld077 -- (xsum#research#consultant#f) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld078 -- (xsum#research#consultant#m) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld079 -- (xsum#research#consultant) 
,SUM(CASE WHEN dept_id = '4' THEN salary ELSE NULL END) AS xfld080 -- (xsum#research) 
,SUM(salary) AS xsum
 FROM xtab_person 
 INNER JOIN xtab_locations 
 ON (xtab_person.loc_id=xtab_locations.loc_id) 
 INNER JOIN xtab_countries 
 ON (xtab_countries.country_id=xtab_locations.country_id)
 GROUP BY Area
UNION
 SELECT 'zzzz' AS Area, 'zzzz' AS country, 'zzzz' AS location
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld001 -- (xcount#pers#employee#f) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld002 -- (xcount#pers#employee#m) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld003 -- (xcount#pers#employee) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld004 -- (xcount#pers#contractor#f) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld005 -- (xcount#pers#contractor#m) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld006 -- (xcount#pers#contractor) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld007 -- (xcount#pers#consultant#f) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld008 -- (xcount#pers#consultant#m) 
,COUNT(CASE WHEN dept_id = '1' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld009 -- (xcount#pers#consultant) 
,COUNT(CASE WHEN dept_id = '1' THEN person_id ELSE NULL END) AS xfld010 -- (xcount#pers) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld011 -- (xcount#xtab_sales#employee#f) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld012 -- (xcount#xtab_sales#employee#m) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld013 -- (xcount#xtab_sales#employee) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld014 -- (xcount#xtab_sales#contractor#f) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld015 -- (xcount#xtab_sales#contractor#m) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld016 -- (xcount#xtab_sales#contractor) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld017 -- (xcount#xtab_sales#consultant#f) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld018 -- (xcount#xtab_sales#consultant#m) 
,COUNT(CASE WHEN dept_id = '2' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld019 -- (xcount#xtab_sales#consultant) 
,COUNT(CASE WHEN dept_id = '2' THEN person_id ELSE NULL END) AS xfld020 -- (xcount#xtab_sales) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld021 -- (xcount#dev#employee#f) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld022 -- (xcount#dev#employee#m) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld023 -- (xcount#dev#employee) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld024 -- (xcount#dev#contractor#f) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld025 -- (xcount#dev#contractor#m) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld026 -- (xcount#dev#contractor) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld027 -- (xcount#dev#consultant#f) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld028 -- (xcount#dev#consultant#m) 
,COUNT(CASE WHEN dept_id = '3' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld029 -- (xcount#dev#consultant) 
,COUNT(CASE WHEN dept_id = '3' THEN person_id ELSE NULL END) AS xfld030 -- (xcount#dev) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld031 -- (xcount#research#employee#f) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld032 -- (xcount#research#employee#m) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '1' THEN person_id ELSE NULL END) AS xfld033 -- (xcount#research#employee) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld034 -- (xcount#research#contractor#f) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld035 -- (xcount#research#contractor#m) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '2' THEN person_id ELSE NULL END) AS xfld036 -- (xcount#research#contractor) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'f' THEN person_id ELSE NULL END) AS xfld037 -- (xcount#research#consultant#f) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'm' THEN person_id ELSE NULL END) AS xfld038 -- (xcount#research#consultant#m) 
,COUNT(CASE WHEN dept_id = '4' AND cat_id = '3' THEN person_id ELSE NULL END) AS xfld039 -- (xcount#research#consultant) 
,COUNT(CASE WHEN dept_id = '4' THEN person_id ELSE NULL END) AS xfld040 -- (xcount#research) 
,COUNT(person_id) AS xcount
,SUM(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld041 -- (xsum#pers#employee#f) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld042 -- (xsum#pers#employee#m) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld043 -- (xsum#pers#employee) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld044 -- (xsum#pers#contractor#f) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld045 -- (xsum#pers#contractor#m) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld046 -- (xsum#pers#contractor) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld047 -- (xsum#pers#consultant#f) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld048 -- (xsum#pers#consultant#m) 
,SUM(CASE WHEN dept_id = '1' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld049 -- (xsum#pers#consultant) 
,SUM(CASE WHEN dept_id = '1' THEN salary ELSE NULL END) AS xfld050 -- (xsum#pers) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld051 -- (xsum#xtab_sales#employee#f) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld052 -- (xsum#xtab_sales#employee#m) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld053 -- (xsum#xtab_sales#employee) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld054 -- (xsum#xtab_sales#contractor#f) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld055 -- (xsum#xtab_sales#contractor#m) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld056 -- (xsum#xtab_sales#contractor) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld057 -- (xsum#xtab_sales#consultant#f) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld058 -- (xsum#xtab_sales#consultant#m) 
,SUM(CASE WHEN dept_id = '2' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld059 -- (xsum#xtab_sales#consultant) 
,SUM(CASE WHEN dept_id = '2' THEN salary ELSE NULL END) AS xfld060 -- (xsum#xtab_sales) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld061 -- (xsum#dev#employee#f) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld062 -- (xsum#dev#employee#m) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld063 -- (xsum#dev#employee) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld064 -- (xsum#dev#contractor#f) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld065 -- (xsum#dev#contractor#m) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld066 -- (xsum#dev#contractor) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld067 -- (xsum#dev#consultant#f) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld068 -- (xsum#dev#consultant#m) 
,SUM(CASE WHEN dept_id = '3' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld069 -- (xsum#dev#consultant) 
,SUM(CASE WHEN dept_id = '3' THEN salary ELSE NULL END) AS xfld070 -- (xsum#dev) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'f' THEN salary ELSE NULL END) AS xfld071 -- (xsum#research#employee#f) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '1' AND gender = 'm' THEN salary ELSE NULL END) AS xfld072 -- (xsum#research#employee#m) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '1' THEN salary ELSE NULL END) AS xfld073 -- (xsum#research#employee) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'f' THEN salary ELSE NULL END) AS xfld074 -- (xsum#research#contractor#f) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '2' AND gender = 'm' THEN salary ELSE NULL END) AS xfld075 -- (xsum#research#contractor#m) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '2' THEN salary ELSE NULL END) AS xfld076 -- (xsum#research#contractor) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'f' THEN salary ELSE NULL END) AS xfld077 -- (xsum#research#consultant#f) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '3' AND gender = 'm' THEN salary ELSE NULL END) AS xfld078 -- (xsum#research#consultant#m) 
,SUM(CASE WHEN dept_id = '4' AND cat_id = '3' THEN salary ELSE NULL END) AS xfld079 -- (xsum#research#consultant) 
,SUM(CASE WHEN dept_id = '4' THEN salary ELSE NULL END) AS xfld080 -- (xsum#research) 
,SUM(salary) AS xsum
 FROM xtab_person 
 INNER JOIN xtab_locations 
 ON (xtab_person.loc_id=xtab_locations.loc_id) 
 INNER JOIN xtab_countries 
 ON (xtab_countries.country_id=xtab_locations.country_id)
 ORDER BY Area, country, location
